name: 'Gradle Pitest with summary comment'
description: 'Action to execute pitest in a project with gradle and leave a comment with the summary of the execution'
inputs:
  repo-token:
    description: 'Repository secret'
    required: true
  reports-retention:
    description: 'Amount of days to retain the reports as artifact'
    required: false
    default: "1"
  reports-path:
    description: 'The path where the pitest reports are generated'
    required: false
    default: "build/reports/pitest"
  working-directory:
    description: 'The directory where gradle can be executed'
    required: false
    default: .
runs:
  using: "composite"
  steps:
    - name: Grant execute permission for gradlew
      working-directory: ${{ inputs.working-directory }}
      run: chmod +x gradlew
      shell: bash

    - name: Build with Gradle
      run: ./gradlew clean assemble
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Execute PITest
      working-directory: ${{ inputs.working-directory }}
      run: |
        MUTATION_TEST=$(./gradlew pitest)     
        SUMMARY=${MUTATION_TEST##*=}
        echo "::set-output name=summary_mutation::$(echo ${SUMMARY%%B*} | sed '/- Statistics/,/Enhanced functionality available at https:\/\/www\.arcmutate\.com\//p' | sed '$d')
      id: mutation-test-execution
      shell: bash

    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        name: reports-artifact
        path: ${{ inputs.reports-path }}
        retention-days: ${{ inputs.reports-retention }}

    - name: Comment on Pull Request
      uses: actions/github-script@v5
      with:
        github-token: ${{ inputs.repo-token }}
        script: |
          const artifactUrl = '${{ steps.artifact-url.outputs.artifact_url }}';
          const prNumber = '${{ github.event.pull_request.number }}';
          const repoOwner = '${{ github.repository_owner }}';
          const repoName = '${{ github.repository_name }}';
          const octokit = github.getOctokit('${{ secrets.GITHUB_TOKEN }}');
          const message = ${{ steps.mutation-test-execution.outputs.summary_mutation }}
          
          await octokit.rest.issues.createComment({
            owner: repoOwner,
            repo: repoName,
            issue_number: prNumber,
            body: message
          });

