name: 'Gradle Pitest with summary comment'
description: 'Action to execute pitest in a project with gradle and leave a comment with the summary of the execution'
inputs:
  repo-token:
    description: 'Repository secret'
    required: true
  reports-retention:
    description: 'Amount of days to retain the reports as artifact'
    required: false
    default: "1"
  reports-path:
    description: 'The path where the pitest reports are generated'
    required: false
    default: "build/reports/pitest"
  working-directory:
    description: 'The directory where gradle can be executed'
    required: false
    default: .
runs:
  using: "composite"
  steps:
    - name: Grant execute permission for gradlew
      working-directory: ${{ inputs.working-directory }}
      run: chmod +x gradlew
      shell: bash

    - name: Build with Gradle
      run: ./gradlew clean assemble
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Execute PITest
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "GITHUB NUMBER"
        echo ${{ github.event.number }}
        MUTATION_TEST=$(./gradlew pitest)     
        SUMMARY=${MUTATION_TEST##*=}
        echo 'summary_mutation<<EOF' >> $GITHUB_ENV      
        echo ${SUMMARY%%B*} | sed 's/>> /\n/g' >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
      id: mutation-test-execution
      shell: bash

    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        name: reports-artifact
        path: ${{ inputs.reports-path }}
        retention-days: ${{ inputs.reports-retention }}

    - name: Comment
      uses: mshick/add-pr-comment@v1
      with:
        message: |
          🧟‍♀ Mutation Testing Summary ️🧟‍♀️
          ================================
          ${{ env.summary_mutation }}
          
          *Check artifacts for the complete report*
        repo-token: ${{ inputs.repo-token }}
        repo-token-user-login: 'github-actions[bot]'
        allow-repeats: true

