name: Pull request

on:
  pull_request:
    branches: [ main ]

jobs:
  execute-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Execute PITest
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: tests

  verify-artifact:
    runs-on: ubuntu-latest

    steps:
        - name: Download artifact
          uses: actions/download-artifact@v2
          with:
            name: reports-artifact
            path: /tmp
        - name: Check if file exists
          run: |
            echo $(ls -1 /tmp)
            if [ -f "/tmp/reports-artifact.zip" ]; then
              echo "File exists."
            else
              echo "File does not exist."
              exit 1
            fi
#  verify-comment:
