name: Pull request

on:
  pull_request_target:
    branches: [ main ]

jobs:
  execute-action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Execute PITest
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: tests
          reports-path: tests/build/reports/pitest

  verify-artifact:
    runs-on: ubuntu-latest
    needs: execute-action
    steps:
        - name: Download artifact
          uses: actions/download-artifact@v3
          with:
            name: reports-artifact
            path: build
        - name: Check if file exists
          run: |
            echo $(ls -l build)
            if [ -f "./build/index.html" ]; then
              echo "File exists."
            else
              echo "File does not exist."
              exit 1
            fi
